### ISSUE TITLE
error when visible-marker package from melpa is used

### ISSUE THREAD

**Issue by ratheesh** [rolandwalker/back-button#4]
I get following error message when `visible-maker` package is enabled with `back-button` package from melpa

`back-button-visible-mark-show: Symbol's function definition is void: visible-mark-initialize-faces`

From the git log of `visible-marker` (https://gitlab.com/iankelling/visible-mark) `visible-mark-initialize-faces` function is removed.

I request you to fix this issue.

Thanks!

**Comment by rolandwalker** [comment]
Thanks!  Fixed in version 0.6.8.
